### ISSUE TITLE
챗봇 답변의 유저 피드백 정보를 받는 기능을 구현합니다.

### ISSUE THREAD

**Issue by kimyoo04** [kimyoo04/seoul-competition-frontend#108]
## 📝 Description

- 챗봇이 답변한 text box에 유저의 피드백을 받을 수 있는 컴포넌트를 추가합니다.

## ☑️ TODO

- [x] 긍정, 부정 반응을 할 수 있는 두 가지 버튼 제작
- [x] type, chatslice 수정
- [x] fetch 함수 제작 및 적용
